"""AIHarness public composition API.

This module is the whole supported surface for applications (`aicode/`,
`personal/`, …). Everything an application needs to assemble a runtime is
re-exported here; anything reachable only through a submodule path is internal
and may change without an ADR.

Deliberately absent: `evals`, `api` and `cli`. Those
packages exist but are not yet injectable into `RunCoordinator`, so there is no
composition contract to promise (TASK.md H-02). They stay on explicit submodule
imports until the Runtime wires them; promoting one means adding its injection
point and an ADR, in that order.

Importing this module must not require any optional extra (`fastapi`,
`psycopg`, `opentelemetry`); `tests/contract/test_public_api.py` enforces that.
"""

from aiharness.agents import (
    SPAWN_CAPABILITY,
    AgentBudget,
    ChildRunSubagentRunner,
    SubagentAuthority,
    SubagentRunner,
    SubagentTool,
    WorkspaceScope,
    restrict_registry,
    subagent_session_factory,
)
from aiharness.artifacts import ArtifactAccess, ArtifactPolicy, ArtifactStore, FileArtifactStore
from aiharness.context import (
    ContextCompiler,
    ContextSection,
    DeterministicSummaryGenerator,
    ModelSummaryGenerator,
    StructuredSummary,
    SummaryGenerator,
    SummaryRequest,
)
from aiharness.core.errors import (
    ContextWindowExceeded,
    EventInvariantViolation,
    HarnessError,
    SandboxViolation,
    SessionNotFound,
    ToolInputError,
    ToolNotFound,
    UnsafeHostNotAcknowledged,
)
from aiharness.core.events import Event
from aiharness.core.ids import new_id
from aiharness.core.types import (
    Capabilities,
    ContentBlock,
    Message,
    ModelRequest,
    ModelResponse,
    StopReason,
    TextBlock,
    ThinkingBlock,
    ToolCallBlock,
    ToolResultBlock,
    ToolSpec,
    Usage,
)
from aiharness.hooks import HookBus
from aiharness.mcp import (
    InMemoryMcpTransport,
    McpClient,
    McpError,
    McpRemoteTool,
    McpServer,
    McpServerTool,
    McpToolAnnotations,
    McpToolDefinition,
    McpTransport,
    StdioMcpTransport,
    register_mcp_tools,
)
from aiharness.memory import (
    InMemoryMemoryStore,
    MemoryAccess,
    MemoryCandidate,
    MemoryCandidateRecorder,
    MemoryContextContributor,
    MemoryKind,
    MemoryRecord,
    MemoryScope,
    MemoryService,
    MemoryStore,
)
from aiharness.models import (
    ROLE_COMPACT,
    ROLE_PRIMARY,
    ROLE_SUBAGENT,
    ModelGateway,
    ModelRoles,
    ModelRouter,
    Provider,
)
from aiharness.models.providers import (
    AnthropicProvider,
    OpenAICompatibleProvider,
    OpenAIProvider,
)
from aiharness.models.providers.fake import FakeProvider
from aiharness.observability import (
    InMemoryTelemetrySink,
    JsonlTelemetrySink,
    Telemetry,
    TelemetrySink,
)
from aiharness.plugins import (
    FileTrustStore,
    PluginCandidate,
    PluginDiscovery,
    PluginHost,
    PluginHostPolicy,
    PluginRemoteTool,
    PluginTrustManager,
    register_plugin_tools,
)
from aiharness.policy import (
    Approval,
    ApprovalOutcome,
    ApprovalRequest,
    ApprovalResolver,
    CapabilityLease,
    Decision,
    DecisionEffect,
    DefaultPolicyEngine,
    PermissionContext,
    PermissionMode,
    PolicyEngine,
    StaticApprovalResolver,
    SuspendingApprovalResolver,
)
from aiharness.runtime import (
    ContextContributor,
    ContextRequest,
    RunCoordinator,
    RunOutcome,
    RunRecorder,
    RunResult,
    RunState,
    RuntimeExtensions,
)
from aiharness.sandbox import (
    DockerBackend,
    HostBackend,
    LocalIsolatedBackend,
    SandboxBackend,
    SandboxDescriptor,
)
from aiharness.sessions import EventStore, InMemoryEventStore, Session, SQLiteEventStore
from aiharness.skills import SkillDiscovery, SkillIndexContributor, SkillRoot, SkillScope
from aiharness.tools import Tool, ToolContext, ToolRegistry, ToolResult
from aiharness.tools.builtin import (
    BashTool,
    EditFileTool,
    GlobTool,
    GrepTool,
    ReadFileTool,
    WriteFileTool,
)

__all__ = [
    "AgentBudget",
    "AnthropicProvider",
    "Approval",
    "ApprovalOutcome",
    "ApprovalRequest",
    "ApprovalResolver",
    "ArtifactAccess",
    "ArtifactPolicy",
    "ArtifactStore",
    "BashTool",
    "Capabilities",
    "CapabilityLease",
    "ChildRunSubagentRunner",
    "ContentBlock",
    "ContextCompiler",
    "ContextContributor",
    "ContextRequest",
    "ContextSection",
    "ContextWindowExceeded",
    "Decision",
    "DecisionEffect",
    "DefaultPolicyEngine",
    "DeterministicSummaryGenerator",
    "DockerBackend",
    "EditFileTool",
    "Event",
    "EventInvariantViolation",
    "EventStore",
    "FakeProvider",
    "FileArtifactStore",
    "FileTrustStore",
    "GlobTool",
    "GrepTool",
    "HarnessError",
    "HookBus",
    "HostBackend",
    "InMemoryEventStore",
    "InMemoryMcpTransport",
    "InMemoryMemoryStore",
    "InMemoryTelemetrySink",
    "JsonlTelemetrySink",
    "LocalIsolatedBackend",
    "McpClient",
    "McpError",
    "McpRemoteTool",
    "McpServer",
    "McpServerTool",
    "McpToolAnnotations",
    "McpToolDefinition",
    "McpTransport",
    "MemoryAccess",
    "MemoryCandidate",
    "MemoryCandidateRecorder",
    "MemoryContextContributor",
    "MemoryKind",
    "MemoryRecord",
    "MemoryScope",
    "MemoryService",
    "MemoryStore",
    "Message",
    "ModelGateway",
    "ModelRequest",
    "ModelResponse",
    "ModelRoles",
    "ModelRouter",
    "ModelSummaryGenerator",
    "OpenAICompatibleProvider",
    "OpenAIProvider",
    "PermissionContext",
    "PermissionMode",
    "PluginCandidate",
    "PluginDiscovery",
    "PluginHost",
    "PluginHostPolicy",
    "PluginRemoteTool",
    "PluginTrustManager",
    "PolicyEngine",
    "Provider",
    "ROLE_COMPACT",
    "ROLE_PRIMARY",
    "ROLE_SUBAGENT",
    "ReadFileTool",
    "RunCoordinator",
    "RunOutcome",
    "RunRecorder",
    "RunResult",
    "RunState",
    "RuntimeExtensions",
    "SPAWN_CAPABILITY",
    "SQLiteEventStore",
    "SandboxBackend",
    "SandboxDescriptor",
    "SandboxViolation",
    "Session",
    "SessionNotFound",
    "SkillDiscovery",
    "SkillIndexContributor",
    "SkillRoot",
    "SkillScope",
    "StaticApprovalResolver",
    "StdioMcpTransport",
    "StopReason",
    "StructuredSummary",
    "SubagentAuthority",
    "SubagentRunner",
    "SubagentTool",
    "SummaryGenerator",
    "SummaryRequest",
    "SuspendingApprovalResolver",
    "Telemetry",
    "TelemetrySink",
    "TextBlock",
    "ThinkingBlock",
    "Tool",
    "ToolCallBlock",
    "ToolContext",
    "ToolInputError",
    "ToolNotFound",
    "ToolRegistry",
    "ToolResult",
    "ToolResultBlock",
    "ToolSpec",
    "UnsafeHostNotAcknowledged",
    "Usage",
    "WorkspaceScope",
    "WriteFileTool",
    "new_id",
    "register_mcp_tools",
    "register_plugin_tools",
    "restrict_registry",
    "subagent_session_factory",
]
__version__ = "0.1.0"
