"""Public composition API for the provider-neutral AIHI Agent Runtime.

This module is the whole supported surface for applications (a coding agent, a
cowork agent, …). Everything an application needs to assemble a runtime is
re-exported here; anything reachable only through a submodule path is internal
and may change without an ADR.

Two kinds of surface live here. The **composition** surface is what an
application injects into a run — a capability only appears once it is reachable
from `RunCoordinator`, so promoting one means adding its injection point first
and an ADR second. The **analysis** surface (`evals`) is the read side: it
consumes a persisted event log after the fact and composes into nothing, so it
carries no injection requirement.

Importing this module must not require any optional extra (`fastapi`,
`psycopg`, `opentelemetry`); the Agent package's public API contract test
enforces that.
"""

from aihi.agent._core.errors import (
    AgentRuntimeError,
    ContextWindowExceeded,
    EventInvariantViolation,
    SandboxViolation,
    SessionNotFound,
    ToolInputError,
    ToolNotFound,
    TurnLimitExceeded,
    UnsafeHostNotAcknowledged,
)
from aihi.agent._core.events import Event
from aihi.agent._core.ids import new_id
from aihi.agent.agents import (
    SPAWN_CAPABILITY,
    AgentBudget,
    AgentState,
    ChildRunSubagentRunner,
    SubagentAuthority,
    SubagentRunner,
    SubagentTool,
    SubagentTypeSpec,
    TaskGraph,
    TaskNode,
    TaskResult,
    TaskSpec,
    WorkspaceScope,
    restrict_registry,
    subagent_session_factory,
)
from aihi.agent.artifacts import ArtifactAccess, ArtifactPolicy, ArtifactStore, FileArtifactStore
from aihi.agent.builder import Runtime, RuntimeBuilder
from aihi.agent.context import (
    ContextCompiler,
    ContextSection,
    DeterministicSummaryGenerator,
    ModelSummaryGenerator,
    StructuredSummary,
    SummaryGenerator,
    SummaryRequest,
)
from aihi.agent.evals import (
    CompositeGrader,
    Delegation,
    EvalError,
    EvalValidationError,
    EventCountGrader,
    GoldenTask,
    GoldenTaskGrader,
    Grade,
    Grader,
    GraphReplayResult,
    ReplayEngine,
    ReplayInvariantViolation,
    ReplayResult,
    RunStateGrader,
    TraceBundle,
    TraceGraph,
    replay_graph,
)
from aihi.agent.hooks import HookBus, HookEvent, HookGovernance, HookOutcome
from aihi.agent.mcp import (
    InMemoryMcpTransport,
    McpClient,
    McpError,
    McpRemoteTool,
    McpServer,
    McpServerTool,
    McpToolAnnotations,
    McpToolDefinition,
    McpTransport,
    StdioMcpTransport,
    register_mcp_tools,
)
from aihi.agent.memory import (
    InMemoryMemoryStore,
    MemoryAccess,
    MemoryCandidate,
    MemoryCandidateRecorder,
    MemoryContextContributor,
    MemoryKind,
    MemoryRecord,
    MemoryScope,
    MemoryService,
    MemoryStore,
)
from aihi.agent.observability import (
    InMemoryTelemetrySink,
    JsonlTelemetrySink,
    Telemetry,
    TelemetrySink,
)
from aihi.agent.plugins import (
    FileTrustStore,
    PluginCandidate,
    PluginDiscovery,
    PluginHost,
    PluginHostPolicy,
    PluginRemoteTool,
    PluginTrustManager,
    register_plugin_tools,
)
from aihi.agent.policy import (
    Approval,
    ApprovalOutcome,
    ApprovalRequest,
    ApprovalResolver,
    CapabilityLease,
    Decision,
    DecisionEffect,
    DefaultPolicyEngine,
    PermissionContext,
    PermissionMode,
    PolicyEngine,
    StaticApprovalResolver,
    SuspendingApprovalResolver,
    approval_input_preview,
)
from aihi.agent.runtime import (
    ContextContributor,
    ContextRequest,
    RunCoordinator,
    RunOutcome,
    RunRecorder,
    RunResult,
    RunState,
    RuntimeExtensions,
)
from aihi.agent.sandbox import (
    DockerBackend,
    HostBackend,
    LocalIsolatedBackend,
    SandboxBackend,
    SandboxDescriptor,
)
from aihi.agent.sessions import EventStore, InMemoryEventStore, Session, SQLiteEventStore
from aihi.agent.skills import (
    FileSkillTrustStore,
    SkillDiscovery,
    SkillIndexContributor,
    SkillLoader,
    SkillRoot,
    SkillScope,
    SkillTrustManager,
)
from aihi.agent.tools import Tool, ToolContext, ToolExecutionResult, ToolRegistry, ToolSpec
from aihi.agent.tools.builtin import (
    BashTool,
    EditFileTool,
    GlobTool,
    GrepTool,
    ReadFileTool,
    ReadLedger,
    WriteFileTool,
)
from aihi.agent.tools.builtin.bash import resolve_bash

__all__ = [
    "AgentBudget",
    "AgentRuntimeError",
    "AgentState",
    "Approval",
    "ApprovalOutcome",
    "ApprovalRequest",
    "ApprovalResolver",
    "ArtifactAccess",
    "ArtifactPolicy",
    "ArtifactStore",
    "BashTool",
    "CapabilityLease",
    "ChildRunSubagentRunner",
    "CompositeGrader",
    "ContextCompiler",
    "ContextContributor",
    "ContextRequest",
    "ContextSection",
    "ContextWindowExceeded",
    "Decision",
    "DecisionEffect",
    "DefaultPolicyEngine",
    "Delegation",
    "DeterministicSummaryGenerator",
    "DockerBackend",
    "EditFileTool",
    "EvalError",
    "EvalValidationError",
    "Event",
    "EventCountGrader",
    "EventInvariantViolation",
    "EventStore",
    "FileArtifactStore",
    "FileSkillTrustStore",
    "FileTrustStore",
    "GlobTool",
    "GoldenTask",
    "GoldenTaskGrader",
    "Grade",
    "Grader",
    "GraphReplayResult",
    "GrepTool",
    "HookBus",
    "HookEvent",
    "HookGovernance",
    "HookOutcome",
    "HostBackend",
    "InMemoryEventStore",
    "InMemoryMcpTransport",
    "InMemoryMemoryStore",
    "InMemoryTelemetrySink",
    "JsonlTelemetrySink",
    "LocalIsolatedBackend",
    "McpClient",
    "McpError",
    "McpRemoteTool",
    "McpServer",
    "McpServerTool",
    "McpToolAnnotations",
    "McpToolDefinition",
    "McpTransport",
    "MemoryAccess",
    "MemoryCandidate",
    "MemoryCandidateRecorder",
    "MemoryContextContributor",
    "MemoryKind",
    "MemoryRecord",
    "MemoryScope",
    "MemoryService",
    "MemoryStore",
    "ModelSummaryGenerator",
    "PermissionContext",
    "PermissionMode",
    "PluginCandidate",
    "PluginDiscovery",
    "PluginHost",
    "PluginHostPolicy",
    "PluginRemoteTool",
    "PluginTrustManager",
    "PolicyEngine",
    "ReadFileTool",
    "ReadLedger",
    "ReplayEngine",
    "ReplayInvariantViolation",
    "ReplayResult",
    "RunCoordinator",
    "RunOutcome",
    "RunRecorder",
    "RunResult",
    "RunState",
    "RunStateGrader",
    "Runtime",
    "RuntimeBuilder",
    "RuntimeExtensions",
    "SPAWN_CAPABILITY",
    "SQLiteEventStore",
    "SandboxBackend",
    "SandboxDescriptor",
    "SandboxViolation",
    "Session",
    "SessionNotFound",
    "SkillDiscovery",
    "SkillIndexContributor",
    "SkillLoader",
    "SkillRoot",
    "SkillScope",
    "SkillTrustManager",
    "StaticApprovalResolver",
    "StdioMcpTransport",
    "StructuredSummary",
    "SubagentAuthority",
    "SubagentRunner",
    "SubagentTool",
    "SubagentTypeSpec",
    "SummaryGenerator",
    "SummaryRequest",
    "SuspendingApprovalResolver",
    "TaskGraph",
    "TaskNode",
    "TaskResult",
    "TaskSpec",
    "Telemetry",
    "TelemetrySink",
    "Tool",
    "ToolContext",
    "ToolExecutionResult",
    "ToolInputError",
    "ToolNotFound",
    "ToolRegistry",
    "ToolSpec",
    "TraceBundle",
    "TraceGraph",
    "TurnLimitExceeded",
    "UnsafeHostNotAcknowledged",
    "WorkspaceScope",
    "WriteFileTool",
    "approval_input_preview",
    "new_id",
    "register_mcp_tools",
    "register_plugin_tools",
    "replay_graph",
    "resolve_bash",
    "restrict_registry",
    "subagent_session_factory",
]
__version__ = "0.1.0"
